//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công..
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không được trùng nhau!.
        /// </summary>
        internal static string DuplicatedValue {
            get {
                return ResourceManager.GetString("DuplicatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tìm thấy dữ liệu nào tương ứng!.
        /// </summary>
        internal static string ErrorMsg_CannotFindData {
            get {
                return ResourceManager.GetString("ErrorMsg.CannotFindData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ!.
        /// </summary>
        internal static string ErrorMsg_DataIsNotValidate {
            get {
                return ResourceManager.GetString("ErrorMsg.DataIsNotValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu nào được xóa..
        /// </summary>
        internal static string ErrorMsg_DeleteFail {
            get {
                return ResourceManager.GetString("ErrorMsg.DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Vui lòng liên hệ với MISA để được hỗ trợ!.
        /// </summary>
        internal static string ErrorMsg_ExceptionOccur {
            get {
                return ResourceManager.GetString("ErrorMsg.ExceptionOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu nào được thêm mới..
        /// </summary>
        internal static string ErrorMsg_InsertFail {
            get {
                return ResourceManager.GetString("ErrorMsg.InsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không tồn tại! Vui lòng kiểm tra lại..
        /// </summary>
        internal static string ErrorMsg_NoDataExists {
            get {
                return ResourceManager.GetString("ErrorMsg.NoDataExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào được thêm. Vui lòng kiển tra lại..
        /// </summary>
        internal static string ErrorMsg_NoRecordAddInDB {
            get {
                return ResourceManager.GetString("ErrorMsg.NoRecordAddInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thông tin nào được cập nhật !.
        /// </summary>
        internal static string ErrorMsg_UpdateFail {
            get {
                return ResourceManager.GetString("ErrorMsg.UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm mới bản ghi..
        /// </summary>
        internal static string InsertSuccess {
            get {
                return ResourceManager.GetString("InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được phét xóa dữ liệu này!.
        /// </summary>
        internal static string NotAllowDeleteThisData {
            get {
                return ResourceManager.GetString("NotAllowDeleteThisData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không được để trống!.
        /// </summary>
        internal static string RequiredValue {
            get {
                return ResourceManager.GetString("RequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công dữ liệu..
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
